# Generated by Django 3.2 on 2023-04-30 15:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20230429_2131"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Preparation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hour",
                    models.CharField(
                        choices=[
                            ("0", "0:00"),
                            ("1", "1:00"),
                            ("2", "2:00"),
                            ("3", "3:00"),
                            ("4", "4:00"),
                            ("5", "5:00"),
                            ("6", "6:00"),
                            ("7", "7:00"),
                            ("8", "8:00"),
                            ("9", "9:00"),
                            ("10", "10:00"),
                            ("11", "11:00"),
                            ("12", "12:00"),
                            ("13", "13:00"),
                            ("14", "14:00"),
                            ("15", "15:00"),
                            ("16", "16:00"),
                            ("17", "17:00"),
                            ("18", "18:00"),
                            ("19", "19:00"),
                            ("20", "20:00"),
                            ("21", "21:00"),
                            ("22", "22:00"),
                            ("23", "23:00"),
                        ],
                        max_length=5,
                        verbose_name="Hour of the day",
                    ),
                ),
                (
                    "temperature",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coffees",
                        to="api.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "audithistory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.audithistory",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("comment", models.TextField()),
                (
                    "coffee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.coffee",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_preps",
                        to="api.preparation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("api.audithistory",),
        ),
    ]
