# Generated by Django 3.2 on 2023-05-05 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_audithistory_brand_coffee_preparation_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='users',
            field=models.ManyToManyField(related_name='brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coffee',
            name='users',
            field=models.ManyToManyField(related_name='coffees', to=settings.AUTH_USER_MODEL),
        ),
    ]
