# Generated by Django 3.2 on 2023-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_add_favorites_to_coffees_brands"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
